site_name: EmbeddingFramework Documentation
site_description: Comprehensive documentation for the EmbeddingFramework Python package
site_author: EmbeddingFramework Team
repo_url: https://github.com/isathish/embeddingframework
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
  - navigation.tabs
  - navigation.sections
  - toc.integrate
  - content.code.copy
nav:
- Home: index.md
- Getting Started:
  - Installation: getting-started/installation.md
  - Quick Start: getting-started/quick-start.md
- Features:
  - Overview: features/index.md
  - Vector Databases: features/vector-databases.md
  - Cloud Storage: features/cloud-storage.md
  - Embedding Providers: features/embedding-providers.md
  - File Processing: features/file-processing.md
  - Utilities: features/utilities.md
- Modules:
  - Adapters: modules/adapters.md
  - Processors: modules/processors.md
  - Utils: modules/utils.md
- Examples:
  - Basic Usage: examples/basic-usage.md
  - Advanced Usage: examples/advanced-usage.md
- Contributing: contributing.md
- License: license.md
markdown_extensions:
- admonition
- codehilite
- footnotes
- meta
- toc:
    permalink: true
